### ISSUE TITLE
Any plans to integrate WebDAV?

### ISSUE THREAD

**Issue by StephanSchrade** [sugeng-sulistiyawan/yii2-flysystem#1]
Hello Sugeng, 
many thanks for your work to integrate the flysystem library to Yii2. This is very helpful.
Do you have any plans to integrate a WebDAV connector as well?
This would be very helpful as this is a wide spread interface which is independent from any vendor.
Regards,
Stephan

**Comment by wanforge** [comment]
With pleasure,

I will soon add WebDAV in the next version..

**Comment by wanforge** [comment]
Added in the following release:

https://github.com/sugeng-sulistiyawan/yii2-flysystem/releases/tag/v1.5.0

Thanks for the feedback
