### ISSUE TITLE
google drive

### ISSUE THREAD

**Issue by paskuale75** [sugeng-sulistiyawan/yii2-flysystem#2]
Is it compatible with Google Drive? thanks

**Comment by wanforge** [comment]
At the moment I haven't implemented it, maybe I will implement it in the next version, you can use https://flysystem.thephpleague.com/docs/adapter/google-cloud-storage/ for now

**Comment by wanforge** [comment]
https://github.com/sugeng-sulistiyawan/yii2-flysystem/releases/tag/v1.7.0
